#############################################################################
# Makefile for building: libpaymentchannel.a
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  paymentchannel.pro
# Template: lib
# Command: /Users/bedeho/Qt/5.5/clang_64/bin/qmake -o Makefile paymentchannel.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -fPIC -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -std=c++11 -stdlib=libc++ -mmacosx-version-min=10.7 -Wall -W $(DEFINES)
INCPATH       = -I. -Iinclude -I/Users/bedeho/JoyStream/Development/paymentchannel-cpp/../common/include -I../../../Qt/5.5/clang_64/lib/QtGui.framework/Headers -I../../../Qt/5.5/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../Qt/5.5/clang_64/mkspecs/macx-clang -F/Users/bedeho/Qt/5.5/clang_64/lib
QMAKE         = /Users/bedeho/Qt/5.5/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = paymentchannel1.0.0
DISTDIR = /Users/bedeho/JoyStream/Development/paymentchannel-cpp/.tmp/paymentchannel1.0.0
AR            = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/RedeemScript.cpp \
		src/Commitment.cpp \
		src/Payee.cpp \
		src/Refund.cpp \
		src/Settlement.cpp \
		src/Payor.cpp \
		src/UnspentBuyerRefundOutput.cpp \
		src/ContractTransactionBuilder.cpp 
OBJECTS       = RedeemScript.o \
		Commitment.o \
		Payee.o \
		Refund.o \
		Settlement.o \
		Payor.o \
		UnspentBuyerRefundOutput.o \
		ContractTransactionBuilder.o
DIST          = ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		paymentchannel.pro include/paymentchannel/RedeemScript.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/Payee.hpp \
		include/paymentchannel/Refund.hpp \
		include/paymentchannel/Settlement.hpp \
		include/paymentchannel/Payor.hpp \
		include/paymentchannel/paymentchannel.hpp \
		include/paymentchannel/UnspentBuyerRefundOutput.hpp \
		include/paymentchannel/ContractTransactionBuilder.hpp src/RedeemScript.cpp \
		src/Commitment.cpp \
		src/Payee.cpp \
		src/Refund.cpp \
		src/Settlement.cpp \
		src/Payor.cpp \
		src/UnspentBuyerRefundOutput.cpp \
		src/ContractTransactionBuilder.cpp
QMAKE_TARGET  = paymentchannel
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libpaymentchannel.a

####### Custom Compiler Variables
QMAKE_COMP_QMAKE_OBJECTIVE_CFLAGS = -pipe \
		-O2 \
		-isysroot \
		/Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk \
		-std=c++11 \
		-stdlib=libc++ \
		-mmacosx-version-min=10.7 \
		-Wall \
		-W



first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)
	$(RANLIB) $(TARGET)


libpaymentchannel.prl: 
	@$(QMAKE) -prl  paymentchannel.pro
Makefile: paymentchannel.pro ../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf ../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/qdevice.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/common/unix.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/macx.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang.conf \
		../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf \
		../../../Qt/5.5/clang_64/mkspecs/qconfig.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/qt.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/resources.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/moc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf \
		../../../Qt/5.5/clang_64/mkspecs/features/lex.prf \
		paymentchannel.pro \
		/Users/bedeho/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl \
		/Users/bedeho/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile paymentchannel.pro
../../../Qt/5.5/clang_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/qdevice.pri:
../../../Qt/5.5/clang_64/mkspecs/features/device_config.prf:
../../../Qt/5.5/clang_64/mkspecs/common/unix.conf:
../../../Qt/5.5/clang_64/mkspecs/common/mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/macx.conf:
../../../Qt/5.5/clang_64/mkspecs/common/sanitize.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.5/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang.conf:
../../../Qt/5.5/clang_64/mkspecs/common/clang-mac.conf:
../../../Qt/5.5/clang_64/mkspecs/qconfig.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.5/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.5/clang_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt_config.prf:
../../../Qt/5.5/clang_64/mkspecs/macx-clang/qmake.conf:
../../../Qt/5.5/clang_64/mkspecs/features/spec_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_pre.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.5/clang_64/mkspecs/features/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/c++11.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/sdk.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/default_post.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/objective_c.prf:
../../../Qt/5.5/clang_64/mkspecs/features/warn_on.prf:
../../../Qt/5.5/clang_64/mkspecs/features/qt.prf:
../../../Qt/5.5/clang_64/mkspecs/features/resources.prf:
../../../Qt/5.5/clang_64/mkspecs/features/moc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.5/clang_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.5/clang_64/mkspecs/features/mac/rez.prf:
../../../Qt/5.5/clang_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.5/clang_64/mkspecs/features/exceptions.prf:
../../../Qt/5.5/clang_64/mkspecs/features/yacc.prf:
../../../Qt/5.5/clang_64/mkspecs/features/lex.prf:
paymentchannel.pro:
/Users/bedeho/Qt/5.5/clang_64/lib/QtGui.framework/QtGui.prl:
/Users/bedeho/Qt/5.5/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile paymentchannel.pro

qmake_all: FORCE


all: Makefile \
		libpaymentchannel.prl $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/paymentchannel/RedeemScript.hpp include/paymentchannel/Commitment.hpp include/paymentchannel/Payee.hpp include/paymentchannel/Refund.hpp include/paymentchannel/Settlement.hpp include/paymentchannel/Payor.hpp include/paymentchannel/paymentchannel.hpp include/paymentchannel/UnspentBuyerRefundOutput.hpp include/paymentchannel/ContractTransactionBuilder.hpp $(DISTDIR)/
	$(COPY_FILE) --parents src/RedeemScript.cpp src/Commitment.cpp src/Payee.cpp src/Refund.cpp src/Settlement.cpp src/Payor.cpp src/UnspentBuyerRefundOutput.cpp src/ContractTransactionBuilder.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash libpaymentchannel.prl
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_objective_c_make_all:
compiler_objective_c_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

RedeemScript.o: src/RedeemScript.cpp include/paymentchannel/RedeemScript.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o RedeemScript.o src/RedeemScript.cpp

Commitment.o: src/Commitment.cpp include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Commitment.o src/Commitment.cpp

Payee.o: src/Payee.cpp include/paymentchannel/Payee.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp \
		include/paymentchannel/Settlement.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Payee.o src/Payee.cpp

Refund.o: src/Refund.cpp include/paymentchannel/Refund.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp \
		include/paymentchannel/UnspentBuyerRefundOutput.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Refund.o src/Refund.cpp

Settlement.o: src/Settlement.cpp include/paymentchannel/Settlement.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Settlement.o src/Settlement.cpp

Payor.o: src/Payor.cpp include/paymentchannel/Payor.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp \
		include/paymentchannel/Refund.hpp \
		include/paymentchannel/Settlement.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Payor.o src/Payor.cpp

UnspentBuyerRefundOutput.o: src/UnspentBuyerRefundOutput.cpp include/paymentchannel/UnspentBuyerRefundOutput.hpp \
		include/paymentchannel/RedeemScript.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o UnspentBuyerRefundOutput.o src/UnspentBuyerRefundOutput.cpp

ContractTransactionBuilder.o: src/ContractTransactionBuilder.cpp include/paymentchannel/ContractTransactionBuilder.hpp \
		include/paymentchannel/Commitment.hpp \
		include/paymentchannel/RedeemScript.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ContractTransactionBuilder.o src/ContractTransactionBuilder.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

